### PR TITLE
Setup Postgres

### PR DESCRIPTION
**Pull request by degoeym**
This is an early attempt at setting up the API to use Postgres.

Getting the EF Core item in place ended up not being all that hard once I figured out the documentation. Main thing is I had to use `2.1.2` of the Npgsql EF implementation for it to work given the version of Microsoft's EF that's being used in the project. I suspect if we upgrade that we can use the latest version.

The catch so far is that by an abstract class it causes the migration to create an...interesting table structure, to say the least. Screenshot below.

image

As you can see, it creates weird column names based on attributes specific to classes that inherit from the abstract `Card` class. I'm thinking to get around this we'll need to have models that are more specific to each card that may include some duplicate fields, and/or we'll need to specify IDs for the classes that inherit from the abstract. I can try both approaches.

Also, ideally we need separate models from our entities. It's the entities that will be used in-code and will need to have transformations to and from the models. Given the models define the DB structure, those can change at any moment so we don't want to have to make tons of changes throughout the code.

Anyone can feel free to pull down this PR to play around with it if they wish, but so far this looks like it'll get us pointed in the right direction.

### CODE REVIEW

**Comment by degoeym** [comment]
Okay, some thoughts on how we've done the abstraction:

1) If we pull `Cost` into the main Card abstraction and make it nullable, that should get rid of the `*_Cost` fields, for which you'll note there is none for `Attachment`, because its property gets mapped first so that "default" `Cost` field is actually for attachment cards. If we pull it into `Card` and make it nullable, then cards that don't have a cost (Holdings and Strongholds) simply won't have values for those fields.
2) Same as above but for `Influence Cost`?
3) Same as above but for `Strength Bonus`?

Either that, or among our models we need to not have the sub-Card types inherit from the main `Card` class through an abstraction and instead use key relationships via property names. Might also be able to more explicitly name fields in the DB so `Cost` becomes `AttachmentCardCost` and `EventCard_Cost` becomes `EventCardCost` using attributes above the properties.

**Comment by programming-wolf** [comment]
> 1. If we pull `Cost` into the main Card abstraction and make it nullable, that should get rid of the `*_Cost` fields, for which you'll note there is none for `Attachment`, because its property gets mapped first so that "default" `Cost` field is actually for attachment cards. If we pull it into `Card` and make it nullable, then cards that don't have a cost (Holdings and Strongholds) simply won't have values for those fields.
> 2. Same as above but for `Influence Cost`?
> 3. Same as above but for `Strength Bonus`?

I don't see Cost duplicated, I only see one Cost field. I guess you mean `Influence Cost`? Like I wrote in the discord channel, we can create one Card table that has all the columns. However, in code, we map various fields to different card implementations, based on a type attribute, for example.

**Comment by degoeym** [comment]
Yeah, what's happening is it's assessing the tables in order, alphabetical it would seem because that's how the files are arranged, so the standalone `Cost` field is for Attachments, then every Cost field after that has `ClassName_` appended to it. There's a few ways I've toyed with that I can get them to be something like `AttachmentCardCost` or just `AttachmentCost`, but that still feels weird to me.

Further, to get things to be fully separated as their own tables we'd have to:

1) Remove the abstraction from the models (we can keep it in the entities).
2) Add an Id field for each card type. This is required for EF because each model needs a primary key associated with it, as that's how EF keeps track of everything.
3) Subsequently it appears we'd have to add `Card` and `CardId` as properties in _every subclass_ for it to properly set up the foreign key relationships, but then we end up with calls like `AttachmentCard.Card.Name` and likely some overly complicated and weird mappings.

We _could_ break things out into just each card type with no abstraction of shared properties, and in some ways it might be cleaner, but yeah, something to think about. Mainly spitballing other possibilities.

**Comment by degoeym** [comment]
I've force pushed the latest migration items. You may want to drop any existing DBs and start fresh, but this should be considered a, "Good enough to get started with the database," set of migrations.

I chose to use Fluent API instead of data annotations. I feel it's better to have these things setup in the `DbContext` rather than littering the models with a bunch of annotations, plus it gives us far greater control of things going forward.

One nice thing about the Fluent API items is it gives us a nice way to cleanly convert the enum values to strings for storing in the database, and then convert them back to the appropriate enum value in the code. The one I'm curious about the most is my setup for converting the list of traits to a list of string and back again. Looks like the migration ran smoothly, but it'll be interesting to see how it works. That said if it _does_ work the way I think it will, we'll have a nice, clean list of human readable traits in the DB which can then be cleanly converted the the appropriate enum when pulling the data back out.

**Comment by degoeym** [comment]
Latest commit:

- Sets up the Keyword items for migrations.
- Adds the migrations to create a new Keyword table.

Though now that I see it, it creates a "Keyword" table when it should be "Keywords", and I'm not seeing other relationships setup the way I'd think they would be.

**Comment by degoeym** [comment]
Table name still not fixed, but the relationship is now there.

**Comment by degoeym** [comment]
Got it, realized what I did wrong. I'm smart.

**Pull request merged**
